name: Publish VSCode Extension

on:
  push:
    branches:
      - test-vsce-publish
  release:
    types:
    - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: VSCE Test
      run: | 
        npm install
        xvfb-run -a npm test
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: VSCE Publish
    if: success() && startsWith(github.ref, 'refs/tags/')
    run: npm run deploy
    env:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}