name: Publish VSCode Extension

on:
  push:
    branches:
      - test-vsce-publish
  release:
    types:
    - created

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qutes-vscode
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Install VSCE with npm
      run: | 
        npm install
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: VSCE Publish
      run: | 
        vsce publish patch | git commit -a -F -
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
