name: Publish VSCode Extension

on:
  push:
    #paths:
     # - qutes-vscode/**
    branches:
      - test-vsce-publish
  release:
    types:
    - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Install npm dependencies
      run: | 
        npm install -g @vscode/vsce
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Publish extension and increment 
      run: | 
        cd qutes-vscode
        vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
